spring:
  application:
    name: graphql-test
  profiles:
    active:
    - dev   
    
---
#Configuración de 'dev'  
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  graphql:
    graphiql:
      enabled: true
