spring:
  application:
    name: graphql-test
  profiles:
    active:
    - dev   
    
---
#Configuración de 'dev'  
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: luisorihuela1992
    url: jdbc:mysql://localhost:3306/spring_graphql
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  graphql:
    graphiql:
      enabled: true
